# -*- coding: utf-8 -*-
"""520_Exercise_2_Submission.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-ZoJ3HTkJeJgZySfYU02sxeapz_vO6fS
"""

import os
os.environ["HF_ALLOW_CODE_EVAL"] = "1"
os.environ["TOKENIZERS_PARALLELISM"] = "false"

import torch
import gc
from datasets import load_dataset
from evaluate import load
from transformers import AutoModelForCausalLM, AutoTokenizer
from tabulate import tabulate
from tqdm import tqdm

model_label_map = {
    "Solshine/Meta-Llama-3.1-8B-Instruct-Python-Coder": "LLaMa",
    "lmsys/vicuna-13b-v1.5": "Vicuna"
}

model_names = list(model_label_map.keys())

all_generations_table = []
results_all = []

for model_name in model_names:
  code_eval = load("code_eval")

  tokenizer = AutoTokenizer.from_pretrained(model_name)
  device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

  model = AutoModelForCausalLM.from_pretrained(
        model_name,
        device_map="auto",
        torch_dtype=torch.float16,
        low_cpu_mem_usage=True
  )
  model.eval()

  for i in tqdm([6, 9], desc=f"{model_label_map[model_name]}"):
      print(f"Inside loop with problem {i}")

      dataset = load_dataset("openai_humaneval")['test'].select([i])

      for problem in dataset:
          entry_point = problem['entry_point']
          test_code = problem['test']
          problem_prompt = problem['prompt']

          if i == 6:
            TEST_CASES = [
                ('(()()) ((())) () ((())()())', [2, 3, 1, 3]),
                ('() (()) ((())) (((())))', [1, 2, 3, 4]),
                ('(()(())((())))', [4]),
                ('(()()) ((())) () ((())()()) (((())))', [2, 3, 1, 3, 4]),
                # provide exactly one more new unique example edge cases here following the format of the examples above
                ('(())', [2])
            ]
            prompt = f"""
                      \"\"\"
                      There is not enough line or branch coverage with the current TEST_CASES array.
                      Return ONLY a modified extended version of the TEST_CASES array with exactly one example that provides more edge cases based on provided assertion statements.
                      The assignment must end with a closing bracket.

                      Current TEST_CASES:
                      {TEST_CASES}

                      Do not generate any functions.

                      Generate only a new modified assignment of TEST_CASES in valid Python syntax like below with exactly one additional example:

                      Return:
                      TEST_CASES = [
                          ('(()()) ((())) () ((())()())', [2, 3, 1, 3]),
                          ('() (()) ((())) (((())))', [1, 2, 3, 4]),
                          ('(()(())((())))', [4]),
                          ('(()()) ((())) () ((())()()) (((())))', [2, 3, 1, 3, 4]),
                          # provide exactly one more new unique example edge cases here following the format of the examples above
                          ('(())', [2])
                      ] # Must provide a closing bracket so the assignment can compile as valid python
                      \"\"\"
                      """
          elif i == 9:
            TEST_CASES = [
                ([], []),
                ([1, 2, 3, 4], [1, 2, 3, 4]),
                ([4, 3, 2, 1], [4, 4, 4, 4]),
                ([3, 2, 3, 100, 3], [3, 3, 3, 100, 100]),
                ([0, 0, 0, 0], [0, 0, 0, 0])
            ]
            prompt = f"""
                        \"\"\"
                        There is not enough line or branch coverage with the current TEST_CASES array.
                        Return ONLY a modified extended version of the TEST_CASES array with exactly one example that provides more edge cases based on provided assertion statements.
                        The assignment must end with a closing bracket.

                        Current TEST_CASES:
                        {TEST_CASES}

                        Do not generate any functions.

                        Generate only a new modified assignment of TEST_CASES in valid Python syntax like below with exactly one additional example:

                        Return:
                        TEST_CASES = [
                            ([], []),
                            ([1, 2, 3, 4], [1, 2, 3, 4]),
                            ([4, 3, 2, 1], [4, 4, 4, 4]),
                            ([3, 2, 3, 100, 3], [3, 3, 3, 100, 100]),
                            ([0, 0, 0, 0], [0, 0, 0, 0]),
                            # provide exactly one more new unique example edge cases here following the format of the examples above
                        ] # Must provide a closing bracket so the assignment can compile as valid python

                        \"\"\"
                        """

          problem_candidates = []
          for _ in range(1):
              inputs = tokenizer(prompt, return_tensors="pt")
              inputs = {k: v.to(device) for k, v in inputs.items()}
              input_len = inputs["input_ids"].shape[1]

              with torch.no_grad():
                  outputs = model.generate(
                      input_ids=inputs["input_ids"],
                      attention_mask=inputs["attention_mask"],
                      max_new_tokens=150,
                      temperature=0.7,
                      top_p=0.95,
                      do_sample=True,
                      eos_token_id=tokenizer.eos_token_id
                  )

              generated_ids = outputs[0][input_len:]
              generated_code = tokenizer.decode(generated_ids, skip_special_tokens=True)
              problem_candidates.append(generated_code)

          all_generations_table.append({
              "Problem ID": i + 1,
              "LLM": model_label_map[model_name],
              "Gen 1": problem_candidates[0],
          })

del model, tokenizer
torch.cuda.empty_cache()
gc.collect()
torch.cuda.ipc_collect()

from tabulate import tabulate

table_str = tabulate(all_generations_table, headers="keys", tablefmt="grid")
print(table_str)

with open("test_case_generation_iteration_three.csv", "w", encoding="utf-8") as f:
    f.write(table_str)

from google.colab import files
files.download("/content/test_case_generation_iteration_three.csv")